# ============================
# 📌 Backend ConfigMap
# ============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  FLASK_ENV: development
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mydb
---
# ============================
# 📌 Backend Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: prasadsb/3-tier:backend-v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: postgres-secrets
---
# ============================
# 📌 Backend Service
# ============================
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
