name: Deploy to GKE with Monitoring
on:
  push:
    branches:
      - main  # Deploy on push to main
  workflow_dispatch: # Allows manual trigger
jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Clones repo to the runner
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: canvas-spark-446913-b1
          export_default_credentials: true
      
      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project canvas-spark-446913-b1
          kubectl version --client
      
      - name: Deploy Manifests to GKE
        run: |
          kubectl apply -f manifest_files/postgres.yaml
          kubectl apply -f manifest_files/backend.yaml
          kubectl apply -f manifest_files/frontend.yaml
      
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version
      
      - name: Add Prometheus and Grafana Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
      
      - name: Check for previous installations
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          helm list -n monitoring || true
          
          # Clean up any previous failed installations if needed
          helm uninstall prometheus -n monitoring || true
          helm uninstall grafana -n monitoring || true
          
          # Small delay to ensure cleanup completes
          sleep 10
      
      - name: Deploy Prometheus
        run: |
          helm upgrade --install prometheus prometheus-community/prometheus \
            --namespace monitoring \
            --set server.persistentVolume.enabled=true \
            --set server.persistentVolume.size=10Gi \
            --timeout 5m
      
      - name: Deploy Grafana
        run: |
          helm upgrade --install grafana grafana/grafana \
            --namespace monitoring \
            --set persistence.enabled=true \
            --set persistence.size=10Gi \
            --set datasources."datasources\.yaml".apiVersion=1 \
            --set datasources."datasources\.yaml".datasources[0].name=Prometheus \
            --set datasources."datasources\.yaml".datasources[0].type=prometheus \
            --set datasources."datasources\.yaml".datasources[0].url=http://prometheus-server.monitoring.svc.cluster.local \
            --set datasources."datasources\.yaml".datasources[0].access=proxy \
            --set datasources."datasources\.yaml".datasources[0].isDefault=true \
            --timeout 5m
      
      - name: Deploy ServiceMonitors for your applications
        run: |
          # Apply custom ServiceMonitor resources to monitor your applications
          kubectl apply -f manifest_files/monitoring/service-monitors.yaml
      
      - name: Import Dashboards to Grafana
        run: |
          # Apply ConfigMaps containing dashboard JSON definitions
          kubectl apply -f manifest_files/monitoring/grafana-dashboards.yaml
      
      - name: Expose monitoring services via LoadBalancer
        run: |
          # Expose Grafana via LoadBalancer
          kubectl patch svc grafana -n monitoring -p '{"spec": {"type": "LoadBalancer"}}'
          
          # Expose Prometheus via LoadBalancer
          kubectl patch svc prometheus-server -n monitoring -p '{"spec": {"type": "LoadBalancer"}}'
          
          # Wait for external IPs to be assigned
          echo "Waiting for LoadBalancer IPs to be assigned..."
          sleep 30
      
      - name: Get monitoring access information
        run: |
          echo "Grafana endpoint:"
          kubectl get svc grafana -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}'
          echo ""
          echo "Grafana admin credentials:"
          echo "Username: admin"
          echo "Password: $(kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode)"
          echo ""
          echo "Prometheus endpoint:"
          kubectl get svc prometheus-server -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}'
          echo ""
      
      - name: Verify Deployment
        run: |
          echo "Application Pods:"
          kubectl get pods
          echo ""
          echo "Monitoring Pods:"
          kubectl get pods -n monitoring
          echo ""
          echo "Monitoring Services with LoadBalancers:"
          kubectl get svc -n monitoring
